# Generated by Django 4.1.1 on 2022-09-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyRestaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="Food",
        ),
    ]
