# Generated by Django 4.1.1 on 2022-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyRestaurant", "0003_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user_id",
            new_name="user",
        ),
    ]
