# Generated by Django 4.1.1 on 2022-09-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyRestaurant", "0005_order_delete_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(default="", upload_to="static/images"),
        ),
    ]
