# Generated by Django 4.1.1 on 2022-09-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0006_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
